### ISSUE TITLE
Pass to google spreadsheet

### ISSUE THREAD

**Issue by AtomikWiWa** [collin-li/pokemon-go-iv-calculator#4]
Hello Collin,

It would be possible to port this project to a google spreadsheet to keep it online.

Thanks,
Edu

**Comment by collin-li** [comment]
Hi Edu, thanks for raising this.

The IV search algorithm is done via a VBA macro. I'm not an expert at Google docs functionality but I assumed that is not that easy to port. Can you confirm or deny?

I have seen Google Sheets IV calculators before though, so it probably is possible but I don't know how much I'd need to "rewrite".

Cheers,
Collin

**Comment by AtomikWiWa** [comment]
Hello again @collin-li ,

I've got some time and I've been able to rewrite your code.

This makes it possible to enter the data online, and have the spreadsheet always accessible.

You want test it here: _(make a copy)_ 

https://docs.google.com/spreadsheets/d/1XD6mgczSTtLkXUqHk_bIOiy1aKtkSwlR1cKr2bfyphA/edit?usp=sharing

Thank you very much, without your code this was not possible.

Best regards,
Eduardo

**Comment by collin-li** [comment]
This is awesome! It looks great and works well. 

I don't play Pokemon regularly any more. I know Gen 3 is coming but I fear I won't be around to update it promptly. I would be very happy if you are using and maintaining this spreadsheet to push updates for other users of this spreadsheet (who are on this Reddit thread: https://www.reddit.com/r/TheSilphRoad/comments/5s56c6/tool_batch_pokemon_calculator_excel_spreadsheet/). I would welcome it if you posted your Google docs version there.

Also, I'm not an expert at GitHub, is there something I should do with this repository if you want to maintain the Google spreadsheet?

**Comment by AtomikWiWa** [comment]
I've been testing with lots of data, and Javascript is very slow to calculate almost 500 rows

It does not work well, I'll do more tests.

**Comment by MizeryMade** [comment]
That's one of the reasons I've preferred this spreadsheet, because it's lightning quick compared to all the online ones that perform sluggishly when opening and entering data.

The original Reddit thread appears to be "closed," by the way. Was going to drop in there and post a suggestion some time ago before finding that you can't post to it anymore.

**Comment by Ch000n** [comment]
I've updated the 'Pokemon Data' sheet with the current values as of Oct 2019 and also added Armored Mewtow and the 4 Deoxys forms, so you may want to update the googledocs. (Will hope to work on Gen 4 and 5 eventually...)
