### ISSUE TITLE
What is...

### ISSUE THREAD

**Issue by LunarLizard** [collin-li/pokemon-go-iv-calculator#7]
Hi, sorry I cant find a way to ask a question or to contact you. 
What are the following iputs boxes for:
C1
DA1
DA4
DB4

I find a reference to these boxes. 
Thanks

**Comment by collin-li** [comment]
Hi LunarLizard,

Thanks for asking - it is not well documented so this is useful:

C1 = number of eggs held, so as to add to the Pokemon Count which is
calculated in A1. I compare the Box Size (e.g. 299/600) with A1 to make
sure I haven't missed anything

DA1, DA4, DB4 can largely be ignored but DA1 is a lucky egg clock. You are
supposed to put in the time in Excel time-date format of when the Lucky Egg
begins, and then as you Evolve Pokemon you change the Remarks column from
"Evolve" to "Evolved" and it will keep track of how fast you are evolving
and track how many evolves will be completed at the current rate. DA4,DB4
are the start and end XP values that you manually input to check whether
the XP gain concords with the amount of evolves you did during the period.
