### ISSUE TITLE
Handling of "Forms" (ie Alolan)

### ISSUE THREAD

**Issue by MizeryMade** [collin-li/pokemon-go-iv-calculator#8]
Hey again Collin. I figure you've probably stopped playing by this point as you had noted dwindling activity some time ago, but thought it couldn't hurt to reach out to see if you had a little time to work something in or had some advice how one might "hack it in themselves" (read, "not very elegantly add" lol).

If you aren't keeping up with the game anymore, Niantic spring-boarded forward to introduce Alolan forms from Gen 7, which are alternate forms of some Kanto pokemon (Gen 1). They have released Exeggutor, and the others seem to be on the horizon. Unlike Castform who has the same stats and it's simply a re-skin and different set of moves -- these pokemon have different stats than their normal counterparts (another example where form handling could come in handy is Deoxys from Gen 3, since it has 4 different forms with different stats). It also currently looks like you can't evolve non-Alolan forms into Alolan forms -- otherwise it could've probably been handled similar to a branched evolution tree.

Having looked into the Pokemon Data sheet in the past, if it were simply a new generation, I could probably figure out adding them in. However, since these are the same 'mon (same Dex#, Name, etc. but different stats)... not sure how/if that could be handled with the current framework you've laid out. The branched evolutions had me stumped upon Gen 3's release, haha.

Any ideas?

**Comment by collin-li** [comment]
Without opening the spreadsheet for probably over a year now, it should be
fairly trivial. The branching structure isn’t really required except to
support the Evolve tab, and so you can really just create new rows with a
unique ID (Pokémon ID which has been the dex number but no reason you can’t
just make them 9999 or something even alphanumeric eg 003A 003B for
different Venusaur forms) for each Alolan form. The IV calculation will
just look up that row and do the work itself. If you need support on the
Evolve tab then you need to map in the family ID and what stage it is.
There may be a few other columns of data you need then it calculates the
branching automatically I believe...

Let me know if it works. I might try have a look when I’m back on a
computer in a week but currently on vacation. Super busy with new life
responsibilities too so can’t promise anything.

**Comment by MizeryMade** [comment]
I took a little time to tinker with it last night, and I seem to have it functioning. Wasn't as hard as I was thinking it was going to be. Just couldn't wrap my head around the logic since they're the same... but not. Haha. It's correctly calculating for Alolan Exeggutor. The evolver tab is just a little wonky because I have them as a part of the same evolution family -- but I as the user know that (as of now), can't evolve between the forms so it's not that big of a deal. I guess I could've given them a different evolution index -- but since they use the same candies... bleh.

I appreciate you taking the time to respond. I figured that you probably had moved on from the game by now based on your comments back around the first Gen 3 dropping, so wasn't sure if you were still watching this project.

Thanks again for having created this wonderful resource!

**Comment by patrickwambacq** [comment]
Hi, would you mind sharing your updated sheet? I too find this an excellent tool, thanks @collin-li, and also @MizeryMade.

**Comment by patrickwambacq** [comment]
Hi, would you mind sharing the updated sheet? I too find this an very useful tool, thanks @collin-li and @MizeryMade.

**Comment by MizeryMade** [comment]
I had gotten a notification email which looked like a reply from someone to this thread about sharing the updated sheet. I don't see a comment here though, so don't know if it was deleted or what. Anyway, I have uploaded my modified sheet to the fork I created... I think? Don't really know much about Github. Haha.

Hope you don't mind Collin, and hope whoever had made that request finds it useful?

**Comment by collin-li** [comment]
Perfect, thanks for that fork. I also can't see PW's post here, but I have it on record in my email.

**Comment by patrickw** [comment]
I wrote that post but removed it immediately when I saw that there was an error in my email address. It took a while before that was fixed because there was something wrong with my account that I could not fix myself.

Yes, I am interested in the updated sheet, thanks for sharing it. Kudos to both of you.
