### ISSUE TITLE
cconfused

### ISSUE THREAD

**Issue by nanogram** [collin-li/pokemon-go-iv-calculator#9]
how do i compile this?? there is no download link...

**Comment by MizeryMade** [comment]
Click to View Code, then just download the XSLM.

**Comment by MizeryMade** [comment]
You may be interested in grabbing my fork though, as I have updated to handle the Alolan forms.

https://github.com/MizeryMade/pokemon-go-iv-calculator

**Comment by nanogram** [comment]
this sounds pretty weak, but how exactly does this work? Do I have to enter in the pokemon manually?

**Comment by nanogram** [comment]
I'm looking for a way to dump the data from pokemon go and add it into a spreadsheet. Do you how to possibly do this?

**Comment by MizeryMade** [comment]
Unfortunately, there is no way of exporting your data from the game automatically. There are some apps (such as CalcyIV for Android) which can read each pokemons data from a screenshot it takes and then stores in a History which can then be exported and manually copied over. However, if you find an app or website that asks for your login information so it can get the data for you.... do not do it. That can get your account banned.
